import Footer from "./commone/Footer";
import Navbar from "./commone/Navbar";
import { UserProvider } from "./context/UserContext";

export const metadata = {
    title: "Zirango",
    description: "Generated by create Zirango app",
  };
const Layout = ({children}) => {
  return (
    <div>
        <Navbar />
         <UserProvider>
         <main>
           {children}
         </main>
         </UserProvider>
        <Footer />
    </div>
  )
}

export default Layout