
import { Poppins } from 'next/font/google';
import "./globals.css";


const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Zirango",
  description: "Generated by create Zirango app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} bg-[#FAF3E0] text-[#222222] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
