import Sitebar from "./sitebar/page";



export const metadata = {
    title: "Zirango",
    description: "Generated by create Zirango app",
  };
const Layout = ({children}) => {
  return (
    <div className="flex flex-row">
      <Sitebar />
      <main>
      {children}
      </main>
    </div>
  )
}

export default Layout